// flow-typed signature: 7681eeaec1bbd20e82016db6dc323a54
// flow-typed version: <<STUB>>/ember-deep-set_vx.x.x/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ember-deep-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ember-deep-set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ember-deep-set/addon/index' {
  declare module.exports: any;
}

declare module 'ember-deep-set/config/ember-try' {
  declare module.exports: any;
}

declare module 'ember-deep-set/config/environment' {
  declare module.exports: any;
}

declare module 'ember-deep-set/ember-cli-build' {
  declare module.exports: any;
}

declare module 'ember-deep-set/testem' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/dummy/app/app' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/dummy/app/resolver' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/dummy/app/router' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/dummy/config/environment' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/helpers/destroy-app' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/helpers/get-path-from' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/helpers/module-for-acceptance' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/helpers/resolver' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/helpers/start-app' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/test-helper' {
  declare module.exports: any;
}

declare module 'ember-deep-set/tests/unit/ember-deep-set-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ember-deep-set/addon/index.js' {
  declare module.exports: $Exports<'ember-deep-set/addon/index'>;
}
declare module 'ember-deep-set/config/ember-try.js' {
  declare module.exports: $Exports<'ember-deep-set/config/ember-try'>;
}
declare module 'ember-deep-set/config/environment.js' {
  declare module.exports: $Exports<'ember-deep-set/config/environment'>;
}
declare module 'ember-deep-set/ember-cli-build.js' {
  declare module.exports: $Exports<'ember-deep-set/ember-cli-build'>;
}
declare module 'ember-deep-set/index' {
  declare module.exports: $Exports<'ember-deep-set'>;
}
declare module 'ember-deep-set/index.js' {
  declare module.exports: $Exports<'ember-deep-set'>;
}
declare module 'ember-deep-set/testem.js' {
  declare module.exports: $Exports<'ember-deep-set/testem'>;
}
declare module 'ember-deep-set/tests/dummy/app/app.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/dummy/app/app'>;
}
declare module 'ember-deep-set/tests/dummy/app/resolver.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/dummy/app/resolver'>;
}
declare module 'ember-deep-set/tests/dummy/app/router.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/dummy/app/router'>;
}
declare module 'ember-deep-set/tests/dummy/config/environment.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/dummy/config/environment'>;
}
declare module 'ember-deep-set/tests/helpers/destroy-app.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/helpers/destroy-app'>;
}
declare module 'ember-deep-set/tests/helpers/get-path-from.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/helpers/get-path-from'>;
}
declare module 'ember-deep-set/tests/helpers/module-for-acceptance.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/helpers/module-for-acceptance'>;
}
declare module 'ember-deep-set/tests/helpers/resolver.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/helpers/resolver'>;
}
declare module 'ember-deep-set/tests/helpers/start-app.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/helpers/start-app'>;
}
declare module 'ember-deep-set/tests/test-helper.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/test-helper'>;
}
declare module 'ember-deep-set/tests/unit/ember-deep-set-test.js' {
  declare module.exports: $Exports<'ember-deep-set/tests/unit/ember-deep-set-test'>;
}
