// flow-typed signature: 9e7723258614058b02df3f10b0c6850f
// flow-typed version: <<STUB>>/ember_vx.x.x/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ember'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ember' {
  declare module.exports: any;
}
declare module '@ember/object' {
  declare module.exports: any;
}
declare module '@ember/array' {
  declare module.exports: any;
}
declare module '@ember/debug' {
  declare module.exports: any;
}
declare module '@ember/utils' {
  declare module.exports: any;
}
declare module '@ember/object/proxy' {
  declare module.exports: any;
}
